classdef ADP < handle
    %ADP Aircraft Design Parameters - Boxwing Freighter ( MTOW)

    properties
        TLAR
        Engine
        AeroPolar
    end

    % Mass properties
    properties
        MTOM    = 319000;   % [kg]  fixed target
        OEM                 % [kg]  calculated by Size.m
        Mf_Ldg  = 0.75;    % landing mass fraction
        Mf_Fuel = 0.28;    % fuel mass fraction  (initial guess)
        Mf_TOC  = 0.98;    % top-of-climb mass fraction
        Mf_res  = 0.04;    % reserve fuel fraction
    end

    % Constraint analysis outputs
    properties
        ThrustToWeightRatio = 0.30;   % initial guess
        WingLoading         = 700;    % [N/m^2] initial guess
    end

    % Aerodynamic properties
    properties
        Cl_max      = 1.7;
        CL_max      = 3.0;
        Delta_Cl_ld = 1.3;
        Delta_Cl_to = 1.0;
        CD_TO       = 0.025;
        CL_TO       = 0.90;
        CD_LDG      = 0.030;
        CL_LDG      = 0.90;
        CL_cruise   = 0.55;
        LD_c        = 21;
        LD_app      = 12;
        CD0         = 0.016;
        e           = 0.95;
        % Boxwing has no conventional tail
        V_HT        = 0;
        V_VT        = 0;
    end

    % Sizing flags
    properties
        isSizeEng  = true;
        isSizeWing = true;
    end

    % Boxwing wing geometry
    properties
        FrontWingSpan = 60;     % [m]
        FrontWingArea = 210;    % [m^2]
        FrontWingPos  = 0;      % [m] set by sizing script

        RearWingSpan  = 60;     % [m]
        RearWingArea  = 210;    % [m^2]
        RearWingPos   = 0;      % [m] set by sizing script

        ConnectorHeight = 8;    % [m] vertical gap between wings

        TotalLiftingArea = 420; % [m^2] updated by updateDerivedProps
        EffectiveSpan    = 50;  % [m]   updated by updateDerivedProps

        Mstar = 0.95;
    end

    % Names used by shared cast / sizing code
    properties
        Thrust   = 0;       % [N] total installed thrust
        WingArea = 420;     % [m^2]  = TotalLiftingArea
        Span     = 50;      % [m]    = EffectiveSpan
        WingPos  = 0;       % [m]    = FrontWingPos
        KinkPos  = 0;       % not used for boxwing

        HtpArea = 0;
        VtpArea = 0;
        HtpPos  = 0;
        VtpPos  = 0;

        c_ac = 0;   % mean aero chord (set by frontwing.m)
        x_ac = 0;   % AC x-position  (set by frontwing.m)
        c_ach = 0;
        c_acv = 0;
    end

    % Fuselage geometry
    properties
        CockpitLength = 6.5;    % [m]
        CabinRadius   = 2.93;   % [m]
        CabinLength   = 0;      % [m] set in constructor
    end

    properties 
        x_ac_rear = 0;
        x_ac_sys = 0;
        MAC = 0;
    end

     properties
        etaLift   = 0.6;  %used to split the amount of lift generated by each wing
        alphaArea = 0.5;  %used to split the area of the front and rear wing
        k_relief   = 0.75; %relief factor from papers listed in methodology
    end
    methods
        function obj = ADP()
            obj.CabinLength = 70.0 - obj.CockpitLength ...
                              - obj.CabinRadius * 2 * 1.48;
        end

        

        function updateDerivedProps(obj)
            % Approximate total wing area split equally front/rear
            % (refine once aero discipline delivers proper sizing)
            obj.FrontWingArea  = obj.WingArea * 0.55;   % ~55% front
            obj.RearWingArea   = obj.WingArea * 0.45;   % ~45% rear           
            L_f = obj.CockpitLength + obj.CabinLength + obj.CabinRadius*1.48;
            obj.FrontWingPos = 0.40 * L_f;
            obj.RearWingPos  = 0.90 * L_f;

            obj.TotalLiftingArea = obj.FrontWingArea + obj.RearWingArea ...
                                 + 2 * obj.ConnectorHeight * 3.5;
            obj.EffectiveSpan    = (obj.FrontWingSpan + obj.RearWingSpan) / 2;
            obj.WingArea         = obj.TotalLiftingArea;
            obj.Span             = obj.EffectiveSpan;
            obj.WingPos          = obj.FrontWingPos;
        end

        function out = AR(obj)
            %AR  Effective aspect ratio of the boxwing lifting system.
            if obj.TotalLiftingArea > 0
                out = obj.EffectiveSpan^2 / obj.TotalLiftingArea;
            else
                out = nan;
            end
        end
        %function updateDerivedProps(obj)
            %UPDATEDERIVEDPROPS  Recalculate derived 
            %  Call this after changing spans, areas, or positions.
        %    obj.TotalLiftingArea = obj.FrontWingArea + obj.RearWingArea ...
        %                         + 2 * obj.ConnectorHeight * 3.5;
        %    obj.EffectiveSpan    = (obj.FrontWingSpan + obj.RearWingSpan) / 2;
        %    obj.WingArea         = obj.TotalLiftingArea;
        %    obj.Span             = obj.EffectiveSpan;
        %    obj.WingPos          = obj.FrontWingPos;
        %end
        
    end
end
