classdef ADP_BW < handle
    %ADP Aircraft Design Parameters for a B777F


    % Top level Design Parameters

    % Masses
    properties
        TLAR
        Engine
        AeroPolar
    end

    properties
        MTOM    % Maximum take-off mass
        OEM     % Operational Empty Mass
        Mf_Ldg  % maximum landing mass fraction (e.g. MLDG = MTOM*Mf_Ldg)
        Mf_Fuel % fuel mass fraction 
        Mf_TOC  % "top of climb" mass fraction
        Mf_res  % "Resevre Fuel" mass fraction
    end
    % constraint Paramters
    properties
        ThrustToWeightRatio  % 
        WingLoading          % 
    end
    % --------------------- Aerodynamic (BoxWing, compatible with tube-wing pipeline) ----------------------
    properties
        % --- Airfoil definition ---
        AirfoilName = "NASA SC(2)-0714";
        tc_ref = 0.14;                 % thickness ratio (midspan reference)

        % --- Section lift characteristics (interpolated from XFOIL @ Re = 1e6, SC(2)-0714) ---
        Re_section_ref   = 1e6;
        Cl_alpha_perdeg  = 0.1233;     % [1/deg]
        Cl_alpha         = 7.06;       % [1/rad]
        alphaL0_deg      = -4.69;      % [deg]
        Cl_max           = 1.77;       % 2D clean section Clmax

        % --- Wing-level lift assumptions (conceptual placeholders) ---
        CL_max     = 1.59;             % 3D CLEAN wing CLmax (no high-lift)
        Delta_Cl_ld = 1.0;             % landing increment
        Delta_Cl_to = 0.8;             % takeoff increment

        % --- Ground run assumptions (TO/Landing config) ---
        CD_TO  = 0.05;
        CL_TO  = 0.8;
        CD_LDG = 0.08;
        CL_LDG = 0.5;

        % --- Cruise condition ---
        CL_cruise;                     % computed in sizing script (leave unset here)

        % --- Aircraft drag polar parameters (cruise) ---
        CD0    = 0.021;                % baseline (replace later with plate build-up)
        e      = 0.97;                 % refers to Wolkovitch (1986)
        CDwave = 0.001;                % wave drag increment near transonic cruise

        % --- Tail volume coefficients (BW defaults) ---
        V_HT = 0.55;
        V_VT = 0.05;

        % --- Ceiling sizing knob ---
        CL_ceiling = 1.0;
        Sweep25 = 30.0; % default sweep at 25% chord, used for Michel's criterion in CD0 estimation, can be overridden by geometry if available

        % Flap drag increments -- Raymer Table 12.7, triple slotted flap
        Delta_CD0_TO = 0.015;   % ***REFINEMENT*** CD0 increment flaps TO
        Delta_CD0_LD = 0.055;   % ***REFINEMENT*** CD0 increment flaps LD
    end

    % Sizing Flags (whether to Adjust certain values during sizing process)
    properties
        isSizeEng = true; % whether to change engine maximum Thrust Value
        isSizeWing = true; % whether to size the wing
    end

    %loop limit
    properties
        %loop lmit
        AR_target = 10;                %AR target (match tube wing) (8-12)
        Span_max = 65; %m
        WS_min = 4.0e3;
        WS_max = 1.30e4;
    end

    % Concrete properties
    properties
        Thrust;

        % planfrom specific
        Span;
        WingArea;
        KinkPos;    % y position of wing kink 
        WingPos;    % Wing position along fuselage
        HtpPos;     % HTP pos along fuselage
        VtpPos;     % VTP pos along fuselage

        Mstar = 0.935; % wing technology factor

        % Empenage Specific
        HtpArea;
        VtpArea
    end

    % useful properties
    properties
        c_ac % mean geometric chord of main wing
        x_ac % x location of mean geometeric chord
        c_ach % mean geometric chord of HTP
        c_acv % mean geometric chord of VTP
    end

    % fuselage properties
    properties
        CockpitLength = 7.3;
        CabinRadius = 2.8;
        CabinLength = 70.8 - 7.3 - 2.8*2*1.48;  % cabin length= Lf_A350- CockpitLength-(1.4*2*CabinRadius)
    end

    properties
        etaLift   = 0.6;  %used to split the amount of lift generated by each wing
        alphaArea = 0.5;  %used to split the area of the front and rear wing
        k_relief   = 0.75; %relief factor from papers listed in methodology
    end

    properties  %wing geometry
        FrontWingPos =  0.4*63.7;
        RearWingPos = 0.7*63.7;
        S_wet_front; %wetted area of front wing, stored from boxwingmass.m
        S_wet_rear;  %wetted area of rear wing, stored from boxwingmass.m
        S_wet_fins;  %wetted area of tip fins, stored from boxwingmass.m
        MAC;         % mean aerodynamic chord, stored from boxwingmass.m
    end

    methods
        function out = AR(obj)
            out = obj.Span.^2./obj.WingArea;
        end
    end
end
